name: API CI

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "api/package-lock.json"

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Run lint
        working-directory: ./api
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "api/package-lock.json"

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Run unit tests
        working-directory: ./api
        run: npm test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: api-unit-test-coverage
          path: api/coverage

  e2e-test:
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [e2e-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy-prd:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

env:
  NODE_ENV: test
